# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(575, 315)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.src_button = QtWidgets.QPushButton(self.centralwidget)
        self.src_button.setGeometry(QtCore.QRect(80, 80, 121, 32))
        self.src_button.setObjectName("src_button")
        self.dst_button = QtWidgets.QPushButton(self.centralwidget)
        self.dst_button.setGeometry(QtCore.QRect(210, 80, 151, 32))
        self.dst_button.setObjectName("dst_button")
        self.sync_button = QtWidgets.QPushButton(self.centralwidget)
        self.sync_button.setGeometry(QtCore.QRect(370, 80, 51, 32))
        self.sync_button.setObjectName("sync_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 575, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.src_button.setText(_translate("MainWindow", "Select a source"))
        self.dst_button.setText(_translate("MainWindow", "Select a destination"))
        self.sync_button.setText(_translate("MainWindow", "Sync"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
